version: "3.9"
services:
  shoko_server:
    container_name: shoko-server
    image: shokoanime/server:daily
    ports:
      - 8111:8111
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - "${SHOKO_ROOT_DIR}:/home/shoko/.shoko"
      - "${ANIME_ROOT_DIR}:/mnt"
      - "${ANIME_IMPORTING_DIR}:/mnt/anime-importing"
      - "${ANIME_PRIVATE_DIR}:/mnt/anime-private"
      - "${ANIME_MOVIE_PRIVATE_DIR}:/mnt/anime-movie-private"
    restart: unless-stopped
    labels:
      - "diun.enable=true"
  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin:latest
    depends_on:
      - shoko_server
    ports:
      - 1900:1900/udp
      - 7359:7359/udp
      - 8000:8000
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID
      - PGID
      - TZ
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - "${JELLYFIN_ROOT_DIR}:/config"
      - "${JELLYFIN_WEB_DIR}:/usr/share/jellyfin/web"
      - "${JELLYFIN_FFMPEG_DIR}:/usr/lib/jellyfin-ffmpeg"
      - "${MUSIC_LIBRARY_DIR}:/music"
      - "${VIDEO_ROOT_DIR}:/video"
      - "${ANIME_PRIVATE_DIR}:/video/anime/anime-private"
      - "${ANIME_MOVIE_PRIVATE_DIR}:/video/anime/anime-movie-private"
    restart: unless-stopped
    labels:
      - "diun.enable=true"
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:develop
    environment:
      - TZ
      - PGID
      - PUID
      - ND_CONFIGFILE=/data/navidrome.toml
    ports:
      - 8097:4533
    volumes:
      - "${NAVIDROME_ROOT_DIR}:/data"
      - "${MUSIC_LIBRARY_DIR}:/music:ro"
      - "${PODCAST_ROOT_DIR}:/podcasts:ro"
    restart: unless-stopped
    labels:
      - "diun.enable=true"
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ
      - PGID
      - PUID
      - WEBUI_PORT=8080
    volumes:
      - "${QBITTORRENT_ROOT_DIR}:/config"
      - "${VIDEO_ROOT_DIR}:/data"
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    labels:
      - "diun.enable=true"
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    depends_on:
      - qbittorrent
    environment:
      - TZ
      - PGID
      - PUID
    volumes:
      - "${PROWLARR_ROOT_DIR}:/config"
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - "diun.enable=true"
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      - qbittorrent
      - prowlarr
    environment:
      - TZ
      - PGID
      - PUID
    volumes:
      - "${SONARR_ROOT_DIR}:/config"
      - "${VIDEO_ROOT_DIR}:/data"
      - "${ANIME_PRIVATE_DIR}:/data/anime/anime-private"
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "diun.enable=true"
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      - qbittorrent
      - prowlarr
    environment:
      - TZ
      - PGID
      - PUID
    volumes:
      - "${RADARR_ROOT_DIR}:/config"
      - "${VIDEO_ROOT_DIR}:/data"
      - "${ANIME_MOVIE_PRIVATE_DIR}:/data/anime/anime-movie-private"
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "diun.enable=true"
  duplicati:
    container_name: duplicati
    image: linuxserver/duplicati:latest
    environment:
      - TZ
      - PGID
      - PUID
    volumes:
      - "${DUPLICATI_ROOT_DIR}:/config"
      - /mnt:/mnt
    ports:
      - 8200:8200
    restart: unless-stopped
    labels:
      - "diun.enabled=true"
  netdata:
    container_name: netdata
    image: netdata/netdata:stable
    privileged: true
    ports:
      - 19999:19999
    environment:
      - TZ
      - PGID=998
      - NETDATA_CLAIM_TOKEN
      - NETDATA_CLAIM_URL
      - NETDATA_CLAIM_ROOMS
    volumes:
      - "${NETDATA_CONFIG_DIR}:/etc/netdata"
      - "${NETDATA_LIB_DIR}:/var/lib/netdata"
      - "${NETDATA_CACHE_DIR}:/var/cache/netdata"
      - "${UNBOUND_ROOT_DIR}:/opt/unbound/etc/unbound"
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-releaase:/host/etc/os-release:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
    labels:
      - "diun.enable=true"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    depends_on:
      - netdata
    volumes:
      - "${PROMETHEUS_ROOT_DIR}:/etc/prometheus"
    environment:
      - TZ
      - PGID
      - PUID
    ports:
      - 9090:9090
    restart: always
    labels:
      - "diun.enable=true"
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    volumes:
      - "${GRAFANA_ROOT_DIR}:/var/lib/grafana"
    environment:
      - TZ
      - PGID
      - PUID
      - GF_AUTH_ANONYMOUS_ENABLED=true
    ports:
      - 3030:3000
    restart: always
    labels:
      - "diun.enable=true"
  tailscale:
    container_name: tailscale
    hostname: tailscale
    image: tailscale/tailscale:stable
    network_mode: host
    privileged: true
    volumes:
      - "${TAILSCALE_ROOT_DIR}:/var/lib"
      - /dev/net/tun:/dev/net/tun
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
    restart: always
    labels:
      - "diun.enable=true"
  unbound:
    container_name: unbound
    image: mvance/unbound:1.16.0
    networks:
      macvlan0:
        ipv4_address: ${UNBOUND_MACVLAN_IP}
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8953:8953/tcp
    volumes:
      - "${UNBOUND_ROOT_DIR}:/opt/unbound/etc/unbound"
    healthcheck:
      disable: true
    restart: always
    labels:
      - "diun.enable=true"
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - unbound
    hostname: pihole
    domainname: local
    mac_address: de:ad:be:ef:ff:01
    networks:
      macvlan0:
        ipv4_address: ${PIHOLE_MACVLAN_IP}
    dns:
      - "${UNBOUND_MACVLAN_IP}"
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 80/udp
    environment:
      - TZ
      - WEBPASSWORD=${PIHOLE_WEBPASSWORD}
      - ServerIP=${PIHOLE_MACVLAN_IP}
      - VIRTUAL_HOST=pihole.local
    volumes:
      - "${PIHOLE_ROOT_DIR}:/etc/pihole"
      - "${PIHOLE_DNSMASQ_DIR}:/etc/dnsmasq.d"
    restart: always
    labels:
      - "diun.enable=true"
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - "${DIUN_DATA_DIR}:/data"
      - "${DIUN_CONFIG_FILE}:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - TZ
      - LOG_LEVEL=info
      - LOG_JSON=false
    restart: always
    labels:
      - "diun.enable=true"

networks:
  macvlan0:
    external: true
