version: "3.9"
services:
  shoko_server:
    container_name: shoko-server
    image: shokoanime/server:daily
    restart: unless-stopped
    network_mode: service:tailscale
    environment:
      - "PUID=${UID}"
      - "PGID=${GID}"
      - TZ=Asia/Manila
      - AVDUMP_MONO=true
    volumes:
      - "${SHOKO_ROOT_DIR}:/home/shoko/.shoko"
      - "${ANIME_ROOT_DIR}:/mnt"
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    network_mode: service:tailscale
    privileged: true
    group_add:
      - 122
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    environment:
      - "PUID=${UID}"
      - "PGID=${GID}"
      - TZ=Asia/Manila
      - JELLYFIN_CACHE_DIR=/config/cache
      - JELLYFIN_CONFIG_DIR=/config/config
      - JELLYFIN_DATA_DIR=/config
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_WEB_DIR=/config/jellyfin-web
      - JELLYFIN_FFMPEG=/config/jellyfin-ffmpeg/ffmpeg
    volumes:
      - "${JELLYFIN_ROOT_DIR}:/config"
      - "${ANIME_LIBRARY_DIR}:/anime"
      - "${MUSIC_LIBRARY_DIR}:/music"
  caddy:
    container_name: caddy
    image:  alexandzors/caddy:latest
    restart: unless-stopped
    network_mode: service:tailscale
    environment:
      - "PUID=${UID}"
      - "PGID=${GID}"
      - TZ=Asia/Manila
    volumes:
      - "${CADDYFILE}:/etc/caddy/Caddyfile:ro"
      - "${CADDY_DATA_DIR}:/data"
      - "${CADDY_CONFIG_DIR}:/config"
      - "${CADDY_LOG_DIR}:/logs"
  tailscale:
    container_name: tristy-tailscale
    hostname: tristy-tailscale
    image: tailscale/tailscale:latest
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
      - "8111:8111"
    volumes:
        - "${TAILSCALE_ROOT_DIR}:/var/lib"
        - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
