version: "3.9"
services:
  shoko_server:
    container_name: shoko-server
    image: shokoanime/server:daily
    restart: unless-stopped
    network_mode: service:tailscale
    environment:
      - "PUID=${UID}"
      - "PGID=${GID}"
      - TZ=Asia/Manila
      - AVDUMP_MONO=true
    volumes:
      - "${SHOKO_ROOT_DIR}:/home/shoko/.shoko"
      - "${ANIME_ROOT_DIR}:/mnt"
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin
    restart: unless-stopped
    network_mode: service:tailscale
    privileged: true
    group_add:
      - "122"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - "PUID=${UID}"
      - "PGID=${GID}"
      - TZ=Asia/Manila
    volumes:
      - "${JELLYFIN_ROOT_DIR}:/config"
      - "${JELLYFIN_WEB_DIR}:/usr/share/jellyfin/web"
      - "${JELLYFIN_FFMPEG_DIR}:/usr/lib/jellyfin-ffmpeg"
      - "${ANIME_LIBRARY_DIR}:/anime"
      - "${MUSIC_LIBRARY_DIR}:/music"
  caddy:
    container_name: caddy
    image: alexandzors/caddy:latest
    restart: unless-stopped
    network_mode: service:tailscale
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
        compress: "true"
    volumes:
      - "${CADDYFILE}:/etc/caddy/Caddyfile:ro"
      - "${CADDY_DATA_DIR}:/data"
      - "${CADDY_CONFIG_DIR}:/config"
  tailscale:
    container_name: tristy-tailscale
    hostname: tristy-tailscale
    image: tailscale/tailscale:latest
    restart: unless-stopped
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
      - "8111:8111"
    volumes:
      - "${TAILSCALE_ROOT_DIR}:/var/lib"
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
