ScanSchedule = '@every 5m'
LogLevel = 'info'
EnableTranscodingConfig = 'false'
ImageCacheSize = '30GB'
TranscodingCacheSize = '50GB'
RecentlyAddedByModTime = 'true'
CoverArtPriority = 'embedded, folder.*, front.*, cover.*, box.*, back.*, external, cdart.*'
CoverJpegQuality = '100'
LastFM.ApiKey = '<replace with lastfm api key>'
LastFM.Secret = '<replace with lastfm secret secret>'
Spotify.ID = '<replace with spotify api key>'
Spotify.Secret = '<replace with spotify api secret>'
UILoginBackgroundUrl = '<replace with image url>'
SearchFullString = 'true'
SubsonicArtistParticipations = 'true'
EnableSharing = 'true'
ArtistArtPriority = 'folder.*, artist.*, external, *.jpg, *.png'
Jukebox.Enabled = 'false'
Scanner.GroupAlbumReleases = 'true'
