Scanner.Schedule = '@every 24h'
LogLevel = 'info'
EnableTranscodingConfig = 'false'
ImageCacheSize = '30GB'
TranscodingCacheSize = '50GB'
RecentlyAddedByModTime = 'true'
CoverArtPriority = 'embedded, folder.*, front.*, cover.*, box.*, back.*, external, cdart.*'
CoverJpegQuality = '100'
LastFM.ApiKey = '<replace with lastfm api key>'
LastFM.Secret = '<replace with lastfm secret secret>'
Spotify.ID = '<replace with spotify api key>'
Spotify.Secret = '<replace with spotify api secret>'
UILoginBackgroundUrl = '<replace with image url>'
SearchFullString = 'true'
Subsonic.ArtistParticipations = 'true'
EnableSharing = 'true'
ArtistArtPriority = 'folder.*, artist.*, external, *.jpg, *.png'
Jukebox.Enabled = 'false'
EnableMediaFileCoverArt = 'false'
Backup.Path = '/data/backups/'
Backup.Count = '3'
Backup.Schedule = '@every 24h'
Subsonic.DefaultReportRealPath = 'true'
EnableReplayGain = 'true'
Tags.mood.Aliases = ['ab:mood']
Scanner.ArtistJoiner = ', '
Tags.author.Aliases = ['author']
Tags.artist.Aliases = ['tpe1', 'artist', '©art', 'iart']
